library(ggplot2)
library(reshape2)
library(beanplot)
library(xlsx)
library(coin)

#path of the resultFPFNAnalysisByProject.csv file generated by experiment.jar
importPath = "C:\\Users\\user\\Desktop\\eis\\results\\" 

#path where the plots will be generated
exportPath = "C:\\Users\\user\\Desktop\\eis\\results\\plots\\"

resultFPFNFile	= "resultFPFNAnalysisByProject.csv"
resultFPFNRaw 	= read.table(file=paste(importPath, resultFPFNFile, sep=""), header=T)

getdata <- function(column1,column2,column3,isrelative){
	data = data.frame(resultFPFNRaw[column1], resultFPFNRaw[column2], resultFPFNRaw[column3])
	if(!isrelative){
		data["RatePercentual"] <- round((data[column3]/data[column2])*100,2)
	} else {
		data["RatePercentual"] <- round((data[column3]/(data[column2]+data[column3]))*100,2)
	}
	
	#withtotal<- computeAndAddTotal(data,column1,column2,column3,"RatePercentual",isrelative,data)
	withmean <- computeAndAddMean(data,column1,column2,column3,"RatePercentual",data)
	withstdv <- computeAndAddStandardDeviation(data,column1,column2,column3,"RatePercentual",withmean)

	return(withstdv)
}

computeAndAddMean <- function(df,column1,column2,column3,column4,target) {
	mean    = mean(df$RatePercentual,na.rm=TRUE)
	nrow    = data.frame("MEAN", "", "",mean)
	colnames(nrow) <- c(column1,column2,column3,column4)
	fa <-rbind(target, nrow)
      return(fa)
}

computeAndAddStandardDeviation <- function(df,column1,column2,column3,column4,target) {
	stddvn  = sd(df$RatePercentual,na.rm = TRUE)
	nrow    = data.frame("STANDARD DEVIATION", "", "",stddvn )
	colnames(nrow) <- c(column1,column2,column3,column4)
	fa <-rbind(target, nrow)
      return(fa)
}

computeAndAddTotal <- function(df,column1,column2,column3,column4,isrelative,target) {
	sum1 	= sum(df[column2])
	sum2 	= sum(df[column3])
	value = 0
	if(!isrelative){
		value <- round((df[column3]/df[column2])*100,2)
	} else {
		value <- round((df[column3]/(df[column2]+df[column3]))*100,2)
	}

	nrow  = data.frame("TOTAL", sum1, sum2,9999) #to replace 9999 by empty
	colnames(nrow) <- c(column1,column2,column3,column4)
	fa <-rbind(target, nrow)
      return(fa)
}

drawboxplot <- function(nd,title,isstmerge){
	theme = theme_set(theme_minimal(base_size = 18))
	theme = theme_update(legend.position="top", legend.title=element_blank(), panel.grid.major.x=element_blank())
	theme = theme_update(axis.text.x=element_blank(), axis.ticks.x = element_blank(), axis.line.x = element_blank(), axis.title.x=element_blank())
	theme = theme_update(axis.text.y=element_blank(), axis.ticks.y = element_blank(), axis.line.y = element_blank(), axis.title.y=element_blank())
	theme = theme_update(axis.line.y = element_blank(), axis.title.y=element_blank(), axis.text.y = element_text(colour="grey"), axis.ticks.y= element_line(colour="grey"))
	boxplot = ggplot(nd ,aes(variable, value, color=variable, fill=variable)) + ggtitle(title) 
	boxplot = boxplot + geom_boxplot(outlier.colour="black", outlier.shape=19,outlier.size=3) 
	boxplot = boxplot + stat_summary(geom = "crossbar", width=1, fatten=0, color="black", fun.data = function(x){ return(c(y=median(x), ymin=median(x), ymax=median(x))) })

	#mean.n <- function(x){ return(c(y = median(x)*0.97, label = round(mean(x),2))) }
	#boxplot = boxplot + stat_summary(fun.data = mean.n, geom = "text", fun.y = mean, colour = "purple")
	
	if(isstmerge){
		boxplot = boxplot + scale_fill_manual(values=c("#E69F00", "#56B4E9"))
	}

	boxplotfile = paste(getRandString(),".png")
	png(paste(exportPath, boxplotfile, sep=""))
	print(boxplot)
	dev.off()
	
	return(boxplotfile)
}


drawplots <- function(faun,fass,isscenario,isfn,isstmerge){
	aux <- head(faun, -3)
	faunpct  = subset(aux, select = c("RatePercentual"))
	faunpct  <- setNames(faunpct, c("Unstructured"))
	
	aux <- head(fass, -3)
	fasspct  = subset(aux, select = c("RatePercentual"))
	fasspct  <- setNames(fasspct, c("Semistructured"))
	
	print(colnames(faun)[3])
	print(wilcox.test(faunpct$Unstructured,fasspct$Semistructured,paired=TRUE))
	print(wilcoxsign_test(faunpct$Unstructured~fasspct$Semistructured, distribution="exact"))

	
	fa <- data.frame(faunpct$Unstructured,fasspct$Semistructured)
	if(isstmerge){
		colnames(fa) <- c("Spacing", "Consecutive Lines")
	}else{
		colnames(fa) <- c("Unstructured", "Semistructured")
	}
	nd <- melt(fa)
	
	if(!isfn){
		if(!isscenario){
			drawboxplot(nd,"Added false positives by conflicts(%)",isstmerge)
		} else {
			drawboxplot(nd,"Added false positives by merge scenarios(%)",isstmerge)
		}
	} else{
		if(!isscenario){
			drawboxplot(nd,"Added false negatives by conflicts(%)",isstmerge)
		} else {
			drawboxplot(nd,"Added false negatives by merge scenarios(%)",isstmerge)
		}
	}
}

getRandString<-function(len=12){
	return(paste(sample(c(rep(0:9,each=5),LETTERS,letters),len,replace=TRUE),collapse=''))
} 

exportDataToExcel <- function(datatoexport){
	fileexcel = paste(getRandString(),".xlsx")
	fileexcel = paste(exportPath, fileexcel, sep="")
	write.xlsx(datatoexport, fileexcel) 
}


main <- function(){
	#false positives
	fpaunscenarios <- getdata("project","mergeScenarios","fpOrderingMergeScenarios",isrelative=FALSE)
	fpassscenarios <- getdata("project","mergeScenarios","fpRenamingMergeScenarios",isrelative=FALSE)
	fpascenariosboxfile <- drawplots(fpaunscenarios,fpassscenarios,isscenario=TRUE,isfn=FALSE,isstmerge=FALSE)
	exportDataToExcel(fpaunscenarios)
	exportDataToExcel(fpassscenarios)

	fpaunconfs <- getdata("project","textualConfUnmerge","fpOrderingConf",isrelative=FALSE)
	fpassconfs <- getdata("project","textualConfSsmerge","fpRenamingConf",isrelative=FALSE)
	fpaconfsboxfile <- drawplots(fpaunconfs ,fpassconfs ,isscenario=FALSE,isfn=FALSE,isstmerge=FALSE)
	exportDataToExcel(fpaunconfs)
	exportDataToExcel(fpassconfs)

	#false negatives
	fnaunscenarios  <- getdata("project","mergeScenarios","fnDuplicationMergeScenarios",isrelative=FALSE)
	fnassscenarios1 <- getdata("project","mergeScenarios","fnImportMergeScenarios",isrelative=FALSE)
	fnassscenarios2 <- getdata("project","mergeScenarios","fnNewArtRefOldOneMergeScnarios",isrelative=FALSE)
	fnassscenarios3 <- getdata("project","mergeScenarios","fnAnonymousMergeScnarios",isrelative=FALSE)
	fnassscenarios4 <- getdata("project","mergeScenarios","addSsFnsScenarios",isrelative=FALSE)
	fnassscenariost <- data.frame(fnassscenarios1["project"],fnassscenarios1["mergeScenarios"],fnassscenarios1["fnImportMergeScenarios"],fnassscenarios2["fnNewArtRefOldOneMergeScnarios"],fnassscenarios3["fnAnonymousMergeScnarios"],fnassscenarios4["addSsFnsScenarios"],fnassscenarios1["RatePercentual"] + fnassscenarios2["RatePercentual"] + fnassscenarios3["RatePercentual"] + fnassscenarios4["RatePercentual"])#joining differents types of fn
	fnascenariosboxfile <- drawplots(fnaunscenarios ,fnassscenariost,isscenario=TRUE ,isfn=TRUE,isstmerge=FALSE)
	exportDataToExcel(fnaunscenarios)
	exportDataToExcel(fnassscenariost)
	
	fnaunconfs  <- getdata("project","textualConfUnmerge","fnDuplicationMissed",isrelative=TRUE)
	fnassconfs1 <- getdata("project","textualConfSsmerge","fnImportMissed",isrelative=TRUE)
	fnassconfs2 <- getdata("project","textualConfSsmerge","fnNewArtRefOldOneConf",isrelative=TRUE)
	fnassconfs3 <- getdata("project","textualConfSsmerge","fnAnonymous",isrelative=TRUE)
	fnassconfs4 <- getdata("project","textualConfSsmerge","addSsFnsConfs",isrelative=TRUE)
	fnassconfst <- data.frame(fnassconfs1["project"],fnassconfs1["textualConfSsmerge"],fnassconfs1["fnImportMissed"],fnassconfs2["fnNewArtRefOldOneConf"],fnassconfs3["fnAnonymous"],fnassconfs4["addSsFnsConfs"],  fnassconfs1["RatePercentual"] + fnassconfs2["RatePercentual"] + fnassconfs3["RatePercentual"]+ fnassconfs4["RatePercentual"])#joining differents types of fn
	fnaconfsboxfile <- drawplots(fnaunconfs,fnassconfst,isscenario=FALSE ,isfn=TRUE,isstmerge=FALSE)
	exportDataToExcel(fnaunconfs)
	exportDataToExcel(fnassconfst)

		
	#HTML code
	##########
	library(R2HTML)
	
	htmlFile = paste(exportPath, "resultFPFN.html", sep="")

	HTML("<link rel=stylesheet type=text/css href=R2HTML.css>", file=htmlFile, append=TRUE)
	
	title = paste("<hr><h1>Results for False Positives and False Negatives Analysis</h1>", sep="")
	
	HTML.title(title, file=htmlFile, append=TRUE)
	
	HTML("<hr><h2>False Positives</h2>", file=htmlFile, append=TRUE)
	
	HTML("<hr><h3>Numbers by Merge Scenarios</h3>", file=htmlFile, append=TRUE)
	
	HTML("<div>", file=htmlFile, append=TRUE)
	HTML("<fieldset>", file=htmlFile, append=TRUE)
	HTML(fpaunscenarios, caption="Unstructured Merge Added False Positives by Merge Scenarios",file=htmlFile, append=TRUE)
	HTML(fpassscenarios, caption="Semistructured Merge Added False Positives by Merge Scenarios", file=htmlFile, append=TRUE)
	HTML("</fieldset>", file=htmlFile, append=TRUE)
	HTML("</div>", file=htmlFile, append=TRUE)
	
	HTML("<hr><h3>Numbers by Conflict</h3>", file=htmlFile, append=TRUE)
	
	HTML("<div>", file=htmlFile, append=TRUE)
	HTML("<fieldset>", file=htmlFile, append=TRUE)
	HTML(fpaunconfs, caption="Unstructured Merge Added False Positives by Conflicts", file=htmlFile, append=TRUE)
	HTML(fpassconfs, caption="Semistructured Merge Added False Positives by Conflicts", file=htmlFile, append=TRUE)
	HTML("</fieldset>", file=htmlFile, append=TRUE)
	HTML("</div>", file=htmlFile, append=TRUE)

	HTML("<hr><h2>False Negatives</h2>", file=htmlFile, append=TRUE)
	
	HTML("<hr><h3>Numbers by Merge Scenario</h3>", file=htmlFile, append=TRUE)
	
	HTML("<div>", file=htmlFile, append=TRUE)
	HTML("<fieldset>", file=htmlFile, append=TRUE)
	HTML(fnaunscenarios, caption="Unstructured Merge Added False Negatives by Merge Scenarios", file=htmlFile, append=TRUE)
	HTML(fnassscenariost, caption="Semistructured Merge Added False Negatives by Merge Scenarios", file=htmlFile, append=TRUE)
	HTML("</div>", file=htmlFile, append=TRUE)
	HTML("</fieldset>", file=htmlFile, append=TRUE)

	HTML("<hr><h3>Numbers by Conflict</h3>", file=htmlFile, append=TRUE)
	
	HTML("<div>", file=htmlFile, append=TRUE)
	HTML("<fieldset>", file=htmlFile, append=TRUE)
	HTML(fnaunconfs, caption="Unstructured Merge Added False Negatives by Conflicts", file=htmlFile, append=TRUE)
	HTML(fnassconfst, caption="Semistructured Merge Added False Negatives by Conflicts", file=htmlFile, append=TRUE)
	HTML("</div>", file=htmlFile, append=TRUE)
	HTML("</fieldset>", file=htmlFile, append=TRUE)
	
	
	HTML("<hr><h2>Plots</h2>", file=htmlFile, append=TRUE)
	
	HTML("<div>", file=htmlFile, append=TRUE)
	HTML("<fieldset>", file=htmlFile, append=TRUE)
	HTMLInsertGraph(file=htmlFile, GraphFileName=fpaconfsboxfile, Align="center", append=TRUE)
	HTMLInsertGraph(file=htmlFile, GraphFileName=fpascenariosboxfile, Align="center", append=TRUE)
	HTML("</div>", file=htmlFile, append=TRUE)
	HTML("</fieldset>", file=htmlFile, append=TRUE)
	

	HTML("<fieldset>", file=htmlFile, append=TRUE)
	HTMLInsertGraph(file=htmlFile, GraphFileName=fnaconfsboxfile, Align="center", append=TRUE)
	HTMLInsertGraph(file=htmlFile, GraphFileName=fnascenariosboxfile, Align="center", append=TRUE)
	HTML("</div>", file=htmlFile, append=TRUE)
	HTML("</fieldset>", file=htmlFile, append=TRUE)
	
	
	time = Sys.time()
	HTML("<hr><h3>Last Time Updated:</h3>", file=htmlFile, append=TRUE)
	HTML(time, file=htmlFile, append=TRUE)

	
}

main()
